name: "PR-Tester"
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  deps:
    name: "Test"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Windows')
        with:
          path: .\Flow-Launcher-Setup.exe
          key: ${{ runner.os }}-flow-
      - name: Download Flow Launcher
        run: |
          if (-Not (Test-Path .\Flow-Launcher-Setup.exe))
          {
            curl.exe -L -o Flow-Launcher-Setup.exe "https://github.com/Flow-Launcher/Flow.Launcher/releases/latest/download/Flow-Launcher-Setup.exe"
          }
      - name: Install Flow Launcher
        run: .\Flow-Launcher-Setup.exe
        shell: cmd

