name: "PR-Tester"
on:
  workflow_dispatch:
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Download a file
        run: Invoke-WebRequest -Uri 'https://github.com/Flow-Launcher/Flow.Launcher/releases/latest/download/Flow-Launcher-Setup.exe' -OutFile './Flow-Launcher-Setup.exe'
      - name: Install Flow Launcher
        run: "& ./Flow-Launcher-Setup.exe"
