name: "PR-Tester"
on:
  workflow_dispatch:
jobs:
  deps:
    name: "Build"
    runs-on: windows-latest
    steps:
      - name: Download a file
        run: |
          curl.exe -L -o Flow-Launcher-Setup.exe "https://github.com/Flow-Launcher/Flow.Launcher/releases/latest/download/Flow-Launcher-Setup.exe"
      - name: Check download
        run: ls
      - name: Install Flow Launcher
        run: |
          Start-Process -FilePath ".\Flow-Launcher-Setup.exe" -PassThru
      - name: Check installation
        run: |
          sleep 15
          ls $env:APPDATA/FlowLauncher

